### ISSUE TITLE
Github not accepting my credentials, per gh.ini.

### ISSUE THREAD

**Issue by 7db9a** [bedardn93/GihtubMakerTools#1]
Github isn't accepting my credentials when trying to create or delete a repo.

My gh.ini

```
[github.org]
User = "7db9a"
Token = "TOKEN"
Organization = "turbo-src"
```

The below is from trying to delete an existing private repo. FYI I tried to delete as a private or public repo to no avail.

```
$ github-maker-tools -d -r TestGithubMakerTool
Traceback (most recent call last):
  File "/usr/src/app/main.py", line 84, in <module>
    main()
  File "/usr/src/app/main.py", line 73, in main
    gh = GithubHandler(user, token, org)
  File "/usr/src/app/main.py", line 14, in __init__
    self.organization = self.git.get_organization(self.org_name)
  File "/usr/local/lib/python3.10/site-packages/github/MainClass.py", line 296, in get_organization
    headers, data = self.__requester.requestJsonAndCheck("GET", f"/orgs/{login}")
  File "/usr/local/lib/python3.10/site-packages/github/Requester.py", line 353, in requestJsonAndCheck
    return self.__check(
  File "/usr/local/lib/python3.10/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.BadCredentialsException: 401 {"message": "Bad credentials", "documentation_url": "https://docs.github.com/rest"}
```

What exact access controls need to be checked off when creating a PAT for this tool? And can you please provide an example of the gh.ini file filled in (with fake token), just in case that's the culprit.

**Comment by bedardn93** [comment]
The token is most likely the cuplrit. The user and organization are important for specifically where you want changes made, but the python Github library uses the token for actually performing actions. From looking at your config file I think the most likely culprit is the quotes in each of the entires. Here's an example of a valid gh.ini that I use to create/delete from an organizational repo.
```
[github.org]
User = bedardn93
Token = ghp_abcdefg
Organization = supertestorg123
```
The configparser doesn't automatically strip quotes, so I think for simplicity I'll add a change to strip the quotes out manually.

**Comment by 7db9a** [comment]
That solved it! I was able to create and delete. Thanks you.
